# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.CharField(max_length=100)),
                ('coin_name', models.CharField(max_length=10)),
                ('last_update', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('avg_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=17)),
                ('coin_num', models.DecimalField(decimal_places=8, default=0.0, max_digits=17)),
                ('is_margin', models.BooleanField(default=False)),
            ],
        ),
    ]
